### ISSUE TITLE
Can proDA be used for paired data?

### ISSUE THREAD

**Issue by hukai916** [const-ae/proDA#12]
Hi, quick question, can proDA perform differentially abundant protein analysis on paired samples?

Thanks!

**Comment by const-ae** [comment]
Hi hukai916,

yes, you would specify the design as.`~ subject + condition`. 

For more background, `proDA` uses a design matrix to specify what kind of model is fit. This is the same approach that is used for (generalized) linear models including  `DESeq2`. I recommend to take a look at its [vignette](https://bioconductor.org/packages/release/bioc/vignettes/DESeq2/inst/doc/DESeq2.html) which goes into great detail explaining how to specify different models including [_how to analyze paired samples_](https://bioconductor.org/packages/release/bioc/vignettes/DESeq2/inst/doc/DESeq2.html#can-i-use-deseq2-to-analyze-paired-samples).


Best,
Constantin
