### ISSUE TITLE
proDA not on CRAN anymore?

### ISSUE THREAD

**Issue by jpquast** [const-ae/proDA#5]
Hi Constantin!

Just a quick question. proDA seems to have disappeared from CRAN. Was this on purpose and will it be available again in the future? It was very nice to be able to install it directly from there. Also a package I am working on has it as a dependency and getting it from CRAN is very convenient in this case.

Maybe you can bring light to the mystery. Thanks in advance!

**Comment by const-ae** [comment]
It's on Bioconductor: http://bioconductor.org/packages/proDA ;)

You can install it via `BiocManager::install("proDA")`
