### ISSUE TITLE
Creating heatmap of protein expression across conditions with proDA package

### ISSUE THREAD

**Issue by arjun0502** [const-ae/proDA#7]
I know that there is a way to create a heatmap of treatment vs. treatment correlation and protein vs. protein correlation with the proDA package, but how do you create a heatmap of protein expression across conditions with the proDA package?

**Comment by const-ae** [comment]
Hi Arjun,

I am very sorry for the for the delayed response. 
The `dist_approx()` function can help you figure out the relation among the samples and proteins:

``` r
library(proDA)
dat <- generate_synthetic_data(n_proteins = 20, 
                     frac_changed = 1,
                     return_summarized_experiment = TRUE)

fit <- proDA(dat, design = ~ group)

d1 <- dist_approx(fit, by_sample = TRUE)
pheatmap::pheatmap(as.matrix(d1$mean), main = "Sample Distances")
```

![](https://i.imgur.com/BQ3dy16.png)

``` r


d2 <- dist_approx(fit, by_sample = FALSE)
pheatmap::pheatmap(as.matrix(d2$mean), main = "Protein Distances")
```

![](https://i.imgur.com/Zc7Fat4.png)

<sup>Created on 2021-01-04 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Best,
Constantin
